export type HfmFixture = {
  markdown: string;
  name: string;
};

export const hfmFixtures = [
  {
    name: 'frontmatter and headings',
    markdown: [
      '---',
      'title: Live Preview',
      'tags: [hackmd, editor]',
      '---',
      '',
      '# Heading',
      '## Subheading',
      'Setext heading',
      '---',
    ].join('\n'),
  },
  {
    name: 'inline formatting and links',
    markdown: '**Strong** and *em* and ~~strike~~ and `code` and [Link](https://hackmd.io).',
  },
  {
    name: 'images with HackMD size syntax',
    markdown: '![Alt](https://example.com/image.png =320x180)',
  },
  {
    name: 'task lists',
    markdown: '- [ ] Task\n- [x] Done',
  },
  {
    name: 'fenced code with metadata',
    markdown: ['```ts=10 [12-13]', 'const value = 1;', '```'].join('\n'),
  },
  {
    name: 'alerts and containers',
    markdown: [
      '> [!note]',
      '> HackMD alert stays editable.',
      '',
      ':::warning',
      'Container fallback stays raw.',
      ':::',
      '',
      ':::spoiler Hidden details',
      'secret',
      ':::',
    ].join('\n'),
  },
  {
    name: 'footnotes',
    markdown: 'Footnote reference[^1].\nInline footnote^[Text of inline footnote] definition.\n\n[^1]: footnote text',
  },
  {
    name: 'ruby mark ins sub and sup',
    markdown: '{漢字|かんじ} ==mark== ++inserted++ H~2~O x^2^',
  },
  {
    name: 'abbr and deflist',
    markdown: '*[HTML]: Hyper Text Markup Language\n\nTerm\n: Definition\n\nTerm 2\n  ~ Compact Definition',
  },
  {
    name: 'emoji and table of contents marker',
    markdown: ':smile: :wink:\n\n[TOC]\n\n[[toc]]',
  },
  {
    name: 'raw html and embed fallback',
    markdown: '<iframe src="https://example.com/embed"></iframe>\n\n<div data-test="raw">Raw HTML</div>',
  },
  {
    name: 'tags heading and blockquote metadata',
    markdown: [
      '###### tags: `features` `cool` `updated`',
      '',
      '> [name=ChengHan Wu] [time=Sun, Jun 28, 2015 9:59 PM] [color=#907bf7]',
      '> > Nested blockquote with metadata.',
    ].join('\n'),
  },
  {
    name: 'code fence line number options',
    markdown: [
      '```javascript=101 [102-103]',
      'console.log("numbered");',
      '```',
      '',
      '```javascript=+',
      'console.log("continue");',
      '```',
      '',
      '```!',
      'A very long line should wrap in HackMD.',
      '```',
    ].join('\n'),
  },
  {
    name: 'csvpreview and all diagram fences',
    markdown: [
      '```csvpreview {header="true" delimiter="."}',
      'firstName.lastName',
      'Jane.Doe',
      '```',
      '',
      '```sequence',
      'Alice->Bob: Hello',
      '```',
      '',
      '```flow',
      'st=>start: Start',
      '```',
      '',
      '```graphviz',
      'digraph hierarchy { Headteacher->Teacher }',
      '```',
      '',
      '```mermaid',
      'graph TD',
      'A-->B',
      '```',
      '',
      '```abc',
      'X:1',
      'K:G',
      '```',
      '',
      '```plantuml',
      'start',
      'stop',
      '```',
      '',
      '```vega',
      '{"mark":"bar"}',
      '```',
      '',
      '```fretboard {title="horizontal, 6 frets, with nut", type="h6"}',
      '-oO-*-',
      '```',
    ].join('\n'),
  },
  {
    name: 'math blocks and inline math',
    markdown: [
      'The Gamma function is $\\Gamma(n) = (n-1)!$.',
      '',
      '$$',
      'x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}.',
      '$$',
    ].join('\n'),
  },
  {
    name: 'HackMD externals',
    markdown: [
      '{%youtube 1G4isv_Fylg %}',
      '{%vimeo 124148255 %}',
      '{%gist schacon/4277 %}',
      '{%slideshare briansolis/26-disruptive-technology-trends-2016-2018-56796196 %}',
      '{%speakerdeck sugarenia/xxlcss-how-to-scale-css-and-keep-your-sanity %}',
      '{%pdf https://hackmd.io/pdf-sample.pdf %}',
      '{%figma https://www.figma.com/file/example %}',
    ].join('\n'),
  },
  {
    name: 'tables links and reference images',
    markdown: [
      '| Option | Description |',
      '| ------: | :---------- |',
      '| data | path to files |',
      '',
      '[link with title](http://nodeca.github.io/pica/demo/ "title text!")',
      'Autoconverted link https://github.com/nodeca/pica',
      '',
      '![Alt text][id]',
      '',
      '[id]: https://octodex.github.com/images/dojocat.jpg "The Dojocat"',
    ].join('\n'),
  },
  {
    name: 'blockquote metadata and raw html icons',
    markdown: [
      '> [name=ChengHan Wu] [time=Sun, Jun 28, 2015 9:59 PM] [color=#907bf7]',
      '> > Nested blockquote with metadata.',
      '',
      '<i class="fa fa-pencil fa-fw"></i> Edit mode',
      '<iframe width="100%" height="500" src="https://hackmd.io/features"></iframe>',
    ].join('\n'),
  },
  {
    name: 'spoiler metadata and typographer samples',
    markdown: [
      ':::spoiler {state="open"} Expand the spoiler container by default',
      'You found me :stuck_out_tongue_winking_eye:',
      ':::',
      '',
      '(c) (C) (r) (R) (tm) (TM) (p) (P) +-',
      'test.. test... test..... test?..... test!....',
      'Remarkable -- awesome',
      '"Smartypants, double quotes"',
      "'Smartypants, single quotes'",
    ].join('\n'),
  },
  {
    name: 'indented code and plain fences',
    markdown: [
      'Indented code',
      '',
      '    // Some comments',
      '    line 1 of code',
      '',
      '```',
      'Sample text here...',
      '```',
    ].join('\n'),
  },
] as const satisfies readonly HfmFixture[];
