/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    fontFamily: {
      brand: ['Inter', 'system-ui', 'sans-serif'],
      'brand-headline': ['Readex Pro', 'system-ui', 'sans-serif'],
      system: ['Inter', 'system-ui', 'sans-serif'],
      'system-code': ['Source Code Pro', 'ui-monospace', 'monospace'],
      editor: ['Source Code Pro', 'ui-monospace', 'monospace'],
    },
    extend: {
      colors: {
        gray: {
          100: '#F8F8F8',
          150: '#F1F1F1',
          200: '#E7E7E7',
          300: '#CDCDCD',
          400: '#BEBEBE',
          500: '#8f8f8f',
          600: '#888888',
          700: '#686868',
          800: '#4f4f4f',
          850: '#484848',
          900: '#262626',
        },
        black: {
          brand: '#333',
        },
        yellow: {
          default: '#F7A004',
          prime: '#EBB047',
          lighter: '#FCF8E3',
          dark: '#816328',
        },
        red: {
          default: '#EA4335',
          light: '#FF6363',
          lighter: '#F2DEDE',
          dark: '#C85C54',
          75: '#FEEEEE',
          '100-60': '#FEE2E299',
          '500-20': '#EF444433',
          '500-40': '#EF444466',
          '900-60': '#7F1D1D99',
        },
        green: {
          default: '#5CB85C',
          light: '#DFF0D8',
          dark: '#4A7543',
          50: '#F6FCF4',
          100: '#D6F1CD',
          200: '#B6E7A6',
          300: '#96DC7F',
          400: '#76D158',
          500: '#59C335',
          600: '#479C2B',
          700: '#357520',
          800: '#234E15',
          900: '#12270B',
        },
        pink: {
          50: '#FFDBEC',
          100: '#FFB7DA',
          200: '#FF94C7',
          300: '#FF70B4',
          400: '#FF4CA2',
          500: '#FF288F',
          600: '#EC0071',
          700: '#B10055',
          800: '#760039',
          900: '#3B001C',
        },
        primary: {
          50: '#ECEBFE',
          100: '#CCCAFC',
          200: '#B2ABFB',
          300: '#9894F9',
          400: '#766DF8',
          500: '#564DFF',
          '500-15': '#564DFF26',
          '500-60': '#564DFF80',
          600: '#453AFF',
          '600-15': '#453AFF26',
          '600-30': '#453AFF4D',
          '600-45': '#453AFF73',
          '600-60': '#453AFF99',
          '600-80': '#453AFFCC',
          700: '#4400FF',
          800: '#2E01A5',
          900: '#24007D',
        },
        sky: {
          '400-10': '#38BDF81A',
        },
        blue: {
          default: '#337AB7',
          dark: '#66B5F0',
          'light-default': '#66B5F0',
          lighter: '#DDECF6',
          lightest: '#F5FAFF',
          hover: '#375F8C',
        },
        amber: {
          75: '#FEF8DD',
          '100-60': '#FEF3C799',
          '400-10': '#FBBF241A',
        },
        emerald: {
          50: '#EFFCF5',
          75: '#E5FBEF',
          100: '#D9F9E5',
          200: '#B8F1D2',
          300: '#8DE4BA',
          400: '#6DB19D',
          '400-15': '#6DB19D26',
          '400-30': '#6DB19D4D',
          500: '#55B685',
          600: '#43946C',
          700: '#347659',
          800: '#295E48',
          900: '#214D3c',
        },
        zinc: {
          25: '#FDFDFD',
          50: '#FAFAFA',
          100: '#F4F4F5',
          200: '#E4E4E7',
          300: '#D4D4D8',
          400: '#A1A1AA',
          500: '#71717A',
          600: '#52525B',
          700: '#3F3F46',
          750: '#303036',
          800: '#27272A',
          850: '#202022',
          900: '#18181B',
          950: '#0E0E10',
        },

        // named colors
        'text-default': 'var(--hmd-tw-text-default)',
        'text-subtle': 'var(--hmd-tw-text-subtle)',
        'text-subtler': 'var(--hmd-tw-text-subtler)',
        'text-emphasize': 'var(--hmd-tw-text-emphasize)',
        'text-primary': 'var(--hmd-tw-text-primary)',
        'text-pink': 'var(--hmd-tw-text-pink)',
        'background-default': 'var(--hmd-tw-background-default)',
        'background-subtle': 'var(--hmd-tw-background-subtle)',
        'background-subtler': 'var(--hmd-tw-background-subtler)',
        'background-sunken': 'var(--hmd-tw-background-sunken)',
        'background-selected': 'var(--hmd-tw-background-selected)',
        'background-primary-default': 'var(--hmd-tw-background-primary-default)',
        'background-primary-subtler': 'var(--hmd-tw-background-primary-subtler)',
        'background-primary-subtle': 'var(--hmd-tw-background-primary-subtle)',
        'background-primary-hover': 'var(--hmd-tw-background-primary-hover)',
        'background-primary-disabled':
          'var(--hmd-tw-background-primary-disabled)',
        'background-primary-focus': 'var(--hmd-tw-background-primary-focus)',
        'background-blur': 'var(--hmd-tw-background-blur)',
        'icon-default': 'var(--hmd-tw-icon-default)',
        'icon-subtle': 'var(--hmd-tw-icon-subtle)',
        'icon-subtler': 'var(--hmd-tw-icon-subtler)',
        'icon-subtlest': 'var(--hmd-tw-icon-subtlest)',
        'icon-disabled': 'var(--hmd-tw-icon-disabled)',
        'icon-primary': 'var(--hmd-tw-icon-primary)',
        'icon-emphasize': 'var(--hmd-tw-icon-emphasize)',
        'border-default': 'var(--hmd-tw-border-default)',
        'border-bold': 'var(--hmd-tw-border-bold)',
        'border-subtle': 'var(--hmd-tw-border-subtle)',
        'border-subtler': 'var(--hmd-tw-border-subtler)',
        'border-subtlest': 'var(--hmd-tw-border-subtlest)',
        'border-primary-focus': 'var(--hmd-tw-border-primary-focus)',
        'border-primary-default': 'var(--hmd-tw-border-primary-default)',
        'border-primary-subtler': 'var(--hmd-tw-border-primary-subtler)',
        overlay: 'var(--hmd-tw-overlay)',
        'state-info-text': 'var(--hmd-tw-state-info-text)',
        'state-info-icon': 'var(--hmd-tw-state-info-icon)',
        'state-info-background': 'var(--hmd-tw-state-info-background)',
        'state-info-border': 'var(--hmd-tw-state-info-border)',
        'state-info-border-subtle': 'var(--hmd-tw-state-info-border-subtle)',
        'state-info-default': 'var(--hmd-tw-state-info-default)',
        'state-success-text': 'var(--hmd-tw-state-success-text)',
        'state-success-icon': 'var(--hmd-tw-state-success-icon)',
        'state-success-background': 'var(--hmd-tw-state-success-background)',
        'state-success-border': 'var(--hmd-tw-state-success-border)',
        'state-success-border-subtle':
          'var(--hmd-tw-state-success-border-subtle)',
        'state-success-default': 'var(--hmd-tw-state-success-default)',
        'state-warning-text': 'var(--hmd-tw-state-warning-text)',
        'state-warning-icon': 'var(--hmd-tw-state-warning-icon)',
        'state-warning-background': 'var(--hmd-tw-state-warning-background)',
        'state-warning-border': 'var(--hmd-tw-state-warning-border)',
        'state-warning-border-subtle':
          'var(--hmd-tw-state-warning-border-subtle)',
        'state-warning-default': 'var(--hmd-tw-state-warning-default)',
        'state-danger-text': 'var(--hmd-tw-state-danger-text)',
        'state-danger-icon': 'var(--hmd-tw-state-danger-icon)',
        'state-danger-bg-light': 'var(--hmd-tw-state-danger-bg-light)',
        'state-danger-bg-default': 'var(--hmd-tw-state-danger-bg-default)',
        'state-danger-bg-hover': 'var(--hmd-tw-state-danger-bg-hover)',
        'state-danger-border': 'var(--hmd-tw-state-danger-border)',
        'state-danger-border-subtle': 'var(--hmd-tw-state-danger-border-subtle)',
        'state-danger-default': 'var(--hmd-tw-state-danger-default)',
        'state-default-background': 'var(--hmd-tw-state-default-background)',
        'element-text-selected': 'var(--hmd-tw-element-text-selected)',
        'element-text-disabled': 'var(--hmd-tw-element-text-disabled)',
        'element-bg-default': 'var(--hmd-tw-element-bg-default)',
        'element-bg-hover': 'var(--hmd-tw-element-bg-hover)',
        'element-bg-disabled': 'var(--hmd-tw-element-bg-disabled)',
        'element-border-hover': 'var(--hmd-tw-element-border-hover)',
        'element-border-focus': 'var(--hmd-tw-element-border-focus)',
        'element-border-error': 'var(--hmd-tw-element-border-error)',
        'element-border-disabled': 'var(--hmd-tw-element-border-disabled)',
        'raised-bg-default': 'var(--hmd-tw-raised-bg-default)',
        'raised-bg-hover': 'var(--hmd-tw-raised-bg-hover)',
        'raised-border-default': 'var(--hmd-tw-raised-border-default)',
        'raised-border-hover': 'var(--hmd-tw-raised-border-hover)',
        'raised-icon-hover': 'var(--hmd-tw-raised-icon-hover)',
        'raised-icon-default': 'var(--hmd-tw-raised-icon-default)',
        'link-text-default': 'var(--hmd-tw-link-text-default)',
        'link-text-hover': 'var(--hmd-tw-link-text-hover)',
        'link-text-pressed': 'var(--hmd-tw-link-text-pressed)',
        'text-mark-comment-default': 'var(--hmd-tw-text-mark-comment-default)',
        'text-mark-comment-selected': 'var(--hmd-tw-text-mark-comment-selected)',
        'text-mark-diff-del': 'var(--hmd-tw-text-mark-diff-del)',
        'text-mark-diff-ins': 'var(--hmd-tw-text-mark-diff-ins)',
        'text-mark-suggest-default': 'var(--hmd-tw-text-mark-suggest-default)',
        'text-mark-suggest-selected': 'var(--hmd-tw-text-mark-suggest-selected)',
        'text-mark-suggest-border': 'var(--hmd-tw-text-mark-suggest-border)',
        'text-mark-paragraph-bookmark-default': 'var(--hmd-tw-text-mark-paragraph-bookmark-default)',
        'text-mark-paragraph-bookmark-selected': 'var(--hmd-tw-text-mark-paragraph-bookmark-selected)',
        'text-mark-paragraph-bookmark-border': 'var(--hmd-tw-text-mark-paragraph-bookmark-border)',
        'prime-border': 'var(--hmd-tw-prime-border)',
        'prime-default': 'var(--hmd-tw-prime-default)',
        'palette-amber-default': 'var(--hmd-tw-palette-amber-default)',
        'palette-emerald-default': 'var(--hmd-tw-palette-emerald-default)',
        'palette-pink-default': 'var(--hmd-tw-palette-pink-default)',
        'palette-sky-default': 'var(--hmd-tw-palette-sky-default)',
        'palette-green-default': 'var(--hmd-tw-palette-green-default)',
        'palette-orange-default': 'var(--hmd-tw-palette-orange-default)',
        'graph-pie-gray-bg': 'var(--hmd-tw-graph-pie-gray-bg)',
        'graph-pie-label-text': 'var(--hmd-tw-graph-pie-label-text)',
        'graph-bar-bg': 'var(--hmd-tw-graph-bar-bg)',
        'community-note-card-book-border': 'var(--hmd-tw-community-note-card-book-border)',
      },
      spacing: {
        0: '0px',
        px: '1px',
        0.5: '2px',
        1: '4px',
        1.25: '5px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        3.75: '15px',
        4: '16px',
        4.5: '18px',
        5: '20px',
        6: '24px',
        6.5: '26px',
        7: '28px',
        7.5: '30px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        14: '56px',
        15: '60px',
        16: '64px',
        20: '80px',
        24: '96px',
        28: '112px',
        32: '128px',
        36: '144px',
        40: '160px',
        44: '176px',
        48: '192px',
        50: '200px',
        52: '208px',
        56: '224px',
        60: '240px',
        64: '256px',
        72: '288px',
        80: '320px',
        96: '384px',
        100: '400px',
        150: '600px',
        224: '900px',
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        md: '6px',
        lg: '8px',
        full: '9999px',
      },
      borderWidth: {
        1: '1px',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        fadeOut: {
          from: { opacity: 1 },
          to: { opacity: 0 },
        },
        dialogIn: {
          '0%': { opacity: 0, transform: 'translateX(-50%) scale(.95)' },
          '100%': { opacity: 1, transform: 'translateX(-50%) scale(1)' },
        },
        dialogOut: {
          '0%': { opacity: 1, transform: 'translateX(-50%) scale(1)' },
          '100%': { opacity: 0, transform: 'translateX(-50%) scale(.95)' },
        },
      },
      animation: {
        'dialog-overlay-in': 'fadeIn 300ms ease-out',
        'dialog-overlay-out': 'fadeOut 200ms ease-in',
        'dialog-in': 'dialogIn 300ms ease-out',
        'dialog-out': 'dialogOut 200ms ease-in',
        'tooltip-in': 'fadeIn 150ms linear',
      },
      backgroundImage: {
        'state-info-background-solid':
          'linear-gradient(var(--hmd-tw-state-info-background), var(--hmd-tw-state-info-background)), ' +
          'linear-gradient(var(--hmd-tw-background-default), var(--hmd-tw-background-default))',
        'state-success-background-solid':
          'linear-gradient(var(--hmd-tw-state-success-background), var(--hmd-tw-state-success-background)), ' +
          'linear-gradient(var(--hmd-tw-background-default), var(--hmd-tw-background-default))',
        'state-warning-background-solid':
          'linear-gradient(var(--hmd-tw-state-warning-background), var(--hmd-tw-state-warning-background)), ' +
          'linear-gradient(var(--hmd-tw-background-default), var(--hmd-tw-background-default))',
        'state-danger-background-solid':
          'linear-gradient(var(--hmd-tw-state-danger-bg-light), var(--hmd-tw-state-danger-bg-light)), ' +
          'linear-gradient(var(--hmd-tw-background-default), var(--hmd-tw-background-default))',
      },
      screens: {
        xs: '600px',
        xl: '1200px',
      },
      dropShadow: {
        tooltip: [
          '0px 1px 3px rgba(0, 0, 0, 0.65)',
          '0px 3px 20px rgba(0, 0, 0, 0.4)',
        ],
      },
      containers: {
        xs: '320px',
        sm: '384px',
        md: '448px',
        lg: '512px',
        xl: '576px',
        '2xl': '672px',
        '3xl': '768px',
        '4xl': '896px',
        '5xl': '1024px',
        '6xl': '1152px',
        '7xl': '1280px',
      },
    },
    fontSize: {
      1: '8px',
      2: '10px',
      3: '12px',
      4: '14px',
      5: '16px',
      6: '18px',
      7: '20px',
      8: '22px',
      9: '24px',
      10: '26px',
      11: '28px',
      12: '30px',
      13: '32px',
      14: '34px',
      15: '36px',
      16: '38px',
      17: '40px',
      18: '42px',
      19: '44px',
      20: '46px',
      21: '48px',
      22: '50px',
      23: '52px',
      24: '54px',
      25: '56px',
      26: '58px',
      27: '60px',
      h1: '26px',
      h2: '22px',
      h3: '18px',
      lg: '16px',
      normal: '14px',
      body: '14px',
      sm: '12px',
      xs: '10px',
    },
    lineHeight: {
      h1: '30px',
      h2: '26px',
      h3: '22px',
      lg: '20px',
      normal: '20px',
      sm: '16px',
      xs: '12px',
    },
  },
  plugins: [require('tailwindcss-animate')],
};
